import { Character } from "../../../../noname/library/element/index.js";

export default {
	gz_caocao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_jianxiong"],
	}),
	gz_simayi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["guicai", "fankui"],
	}),
	gz_xiahoudun: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_ganglie"],
	}),
	gz_zhangliao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_tuxi"],
	}),
	gz_xuzhu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_luoyi"],
	}),
	gz_guojia: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["tiandu", "gz_yiji"],
		hasSkinInGuozhan: true,
	}),
	gz_zhenji: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["luoshen", "qingguo"],
		hasSkinInGuozhan: true,
	}),
	gz_xiahouyuan: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_shensu"],
		hasSkinInGuozhan: true,
	}),
	gz_zhanghe: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_qiaobian"],
	}),
	gz_xuhuang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_duanliang"],
	}),
	gz_caoren: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_jushou"],
	}),
	gz_dianwei: new Character({
		sex: "male",
		group: "wei",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gz_qiangxi"],
		hasSkinInGuozhan: true,
	}),
	gz_xunyu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_quhu", "gz_jieming"],
	}),
	gz_caopi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_xingshang", "gz_fangzhu"],
		hasSkinInGuozhan: true,
	}),
	gz_yuejin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_xiaoguo"],
		hasSkinInGuozhan: true,
	}),

	gz_liubei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_rende"],
	}),
	gz_guanyu: new Character({
		sex: "male",
		group: "shu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gz_wusheng"],
		hasSkinInGuozhan: true,
	}),
	gz_zhangfei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_paoxiao"],
	}),
	gz_zhugeliang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["guanxing", "gz_kongcheng"],
		hasSkinInGuozhan: true,
	}),
	gz_zhaoyun: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_longdan"],
	}),
	gz_machao: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mashu", "gz_tieji"],
	}),
	gz_huangyueying: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["jizhi", "qicai"],
		hasSkinInGuozhan: true,
	}),
	gz_huangzhong: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_liegong"],
		hasSkinInGuozhan: true,
	}),
	gz_weiyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_kuanggu"],
	}),
	gz_pangtong: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["gz_lianhuan", "gz_niepan"],
	}),
	// 后续的武将如果不是本身拥有国战的技能，暂时都摆了，解耦时记得把技能从原来的包拿过来
	// 描述也是
	gz_sp_zhugeliang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["huoji", "bazhen", "kanpo"],
		hasSkinInGuozhan: true,
	}),
	gz_liushan: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["xiangle", "fangquan"],
	}),
	gz_menghuo: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["huoshou", "rezaiqi"],
	}),
	gz_zhurong: new Character({
		sex: "female",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["juxiang", "lieren"],
	}),
	gz_ganfuren: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["gz_shushen", "shenzhi"],
		hasSkinInGuozhan: true,
	}),

	gz_sunquan: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhiheng"],
	}),
	gz_ganning: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qixi"],
	}),
	gz_lvmeng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_keji", "gz_mouduan"],
	}),
	gz_huanggai: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_kurou"],
	}),
	gz_zhouyu: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["reyingzi", "refanjian"],
		hasSkinInGuozhan: true,
	}),
	gz_daqiao: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["guose", "liuli"],
	}),
	gz_luxun: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_qianxun", "gz_duoshi"],
		hasSkinInGuozhan: true,
	}),
	gz_sunshangxiang: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["jieyin", "gz_xiaoji"],
		hasSkinInGuozhan: true,
	}),
	gz_sunjian: new Character({
		sex: "male",
		group: "wu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["yinghun"],
		hasSkinInGuozhan: true,
	}),
	gz_xiaoqiao: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_tianxiang", "gz_hongyan"],
		hasSkinInGuozhan: true,
	}),
	gz_re_taishici: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["tianyi", "gz_hanzhan"],
		tempname: ["re_taishici"],
		dieAudios: ["re_taishici"],
	}),
	gz_zhoutai: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["buqu", "new_fenji"],
	}),
	gz_re_lusu: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["haoshi", "dimeng"],
	}),
	gz_zhangzhang: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhijian", "guzheng"],
	}),
	gz_dingfeng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_duanbing", "fenxun"],
		hasSkinInGuozhan: true,
	}),

	gz_huatuo: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["new_chuli", "jijiu"],
	}),
	gz_lvbu: new Character({
		sex: "male",
		group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gz_wushuang"],
		hasSkinInGuozhan: true,
	}),
	gz_diaochan: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["lijian", "biyue"],
		hasSkinInGuozhan: true,
	}),
	gz_re_yuanshao: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_luanji"],
		hasSkinInGuozhan: true,
	}),
	gz_yanwen: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_shuangxiong"],
	}),
	gz_jiaxu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wansha", "luanwu", "gz_weimu"],
		hasSkinInGuozhan: true,
	}),
	gz_pangde: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mashu", "jianchu"],
	}),
	gz_zhangjiao: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["leiji", "guidao"],
	}),
	gz_caiwenji: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["beige", "gz_duanchang"],
	}),
	gz_mateng: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mashu", "xiongyi"],
	}),
	gz_kongrong: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_mingshi", "lirang"],
	}),
	gz_jiling: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["shuangren"],
	}),
	gz_tianfeng: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["sijian", "gz_suishi"],
	}),
	gz_panfeng: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_kuangfu"],
		hasSkinInGuozhan: true,
	}),
	gz_zoushi: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_huoshui", "gz_qingcheng"],
	}),

	////////////////////////////////////////////////////////////////////
	gz_zhonghui: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakequanji", "fakepaiyi"],
		hasSkinInGuozhan: true,
	}),
	gz_shimazhao: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaoxin", "gzsuzhi"],
		hasSkinInGuozhan: true,
	}),
	gz_gongsunyuan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzhuaiyi", "gzzisui"],
		hasSkinInGuozhan: true,
	}),
	gz_sunchen: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakeshilu", "fakexiongnve"],
		hasSkinInGuozhan: false,
	}),
	gz_tangzi: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxingzhao"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_mengda: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qiuan", "liangfan"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: false,
	}),
	// 刘琦
	gz_liuqi: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwenji", "gztunjiang"],
		doubleGroup: ["qun", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_mifangfushiren: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mffengshi"],
		doubleGroup: ["wu", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_shixie: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiluan", "gzrelixia"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhanglu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzrebushi", "gzremidao"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_dongzhao: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["quanjin", "zaoyun"],
		// doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: false,
	}),
	gz_re_xushu: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhuhai", "gzpozhen", "gzjiancai"],
		hasSkinInGuozhan: true,
	}),
	// 那男舅
	gz_wujing: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["donggui", "fengyang"],
		hasSkinInGuozhan: true,
	}),
	// 严虎
	gz_yanhu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhidao", "gzyjili"],
		hasSkinInGuozhan: true,
	}),
	gz_xuyou: new Character({
		doubleGroup: ["wei", "qun"],
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenglve", "gzshicai"],
		hasSkinInGuozhan: true,
	}),
	/////
	gz_xiahouba: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzbaolie"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_panjun: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzcongcha", "xinfu_gongqing"],
		doubleGroup: ["shu", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_huangzu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxishe"],
		hasSkinInGuozhan: true,
	}),
	gz_zhugeke: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["aocai", "gzduwu"],
		hasSkinInGuozhan: true,
	}),
	gz_wenqin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjinfa"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_xf_sufei: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzlianpian"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_liuba: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongduo", "qingyin"],
		hasSkinInGuozhan: true,
	}),
	gz_pengyang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongling", "gzjinyu"],
		doubleGroup: ["shu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhuling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjuejue", "gzfangyuan"],
		hasSkinInGuozhan: true,
	}),
	gz_wangyi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhenlie", "miji"],
	}),
	gz_wangji: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzqizhi", "gzjinqu"],
	}),
	gz_xurong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxionghuo"],
	}),
	gz_xianglang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzkanji", "dcqianzheng"],
	}),
	gz_tengyin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenjian", "gzxixiu"],
	}),
	gz_re_panshu: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhiren", "gzyaner"],
	}),
	gz_maliang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiemu", "naman"],
		dieAudios: ["old_maliang"],
	}),
	gz_caozhen: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzsidi"],
	}),
	gz_caoang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["kaikang"],
	}),
	gz_bulianshi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["old_anxu", "zhuiyi"],
	}),
	gz_mazhong: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["twfuman"],
	}),
	gz_ol_lisu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiaoyan", "xianzhu"],
	}),

	///
	gz_yuji: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qianhuan"],
		hasSkinInGuozhan: true,
	}),
	gz_dengai: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["tuntian", "ziliang", "gzjixi"],
		hasSkinInGuozhan: true,
	}),
	gz_caohong: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakehuyuan", "heyi"],
		hasSkinInGuozhan: true,
	}),
	gz_jiangfei: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shengxi", "gzshoucheng"],
		hasSkinInGuozhan: true,
	}),
	gz_jiangwei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["tiaoxin", "yizhi", "tianfu"],
		hasSkinInGuozhan: true,
	}),
	gz_xusheng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzyicheng_new"],
		hasSkinInGuozhan: true,
	}),

	gz_re_xusheng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["repolu"],
	}),
	// 怎么还冒出来一个体力上限不一样的呢？
	gz_ol_sb_sunjian: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		hujia: 0,
		skills: ["olsbhulie", "olsbyipo"],
	}),
	gz_jiangqing: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzshangyi", "niaoxiang"],
	}),
	gz_hetaihou: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhendu", "qiluan"],
		hasSkinInGuozhan: true,
	}),

	gz_re_lidian: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xunxun", "wangxi"],
	}),
	gz_zangba: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzhengjiang"],
		img: "image/character/tw_zangba.jpg",
	}),
	gz_madai: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mashu", "qianxi"],
		hasSkinInGuozhan: true,
	}),
	gz_mifuren: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzguixiu", "gzcunsi"],
	}),
	gz_sunce: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jiang", "yingyang", "baka_hunshang"],
		hasSkinInGuozhan: true,
	}),
	gz_chendong: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["duanxie", "fakefenming"],
		hasSkinInGuozhan: true,
	}),
	gz_sp_dongzhuo: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["hengzheng", "fakebaoling"],
	}),
	gz_zhangren: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["chuanxin", "fengshi"],
	}),

	gz_jun_liubei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhangwu", "jizhao", "shouyue"],
	}),
	gz_jun_zhangjiao: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["wuxin", "hongfa", "wendao"],
	}),
	gz_jun_sunquan: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jiahe", "lianzi", "jubao"],
	}),

	gz_liqueguosi: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxiongsuan"],
		hasSkinInGuozhan: true,
	}),
	gz_zuoci: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeyigui", "fakejihun"],
		hasSkinInGuozhan: true,
	}),
	gz_bianfuren: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wanwei", "gzyuejian"],
		dieAudios: ["ol_bianfuren"],
	}),
	gz_xunyou: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzqice", "zhiyu"],
		hasSkinInGuozhan: true,
	}),
	gz_lingtong: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xuanlve", "yongjin"],
		hasSkinInGuozhan: true,
	}),
	gz_lvfan: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdiaodu_backports", "gzdiancai"],
		hasSkinInGuozhan: true,
	}),
	gz_masu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzsanyao", "gzzhiman"],
		hasSkinInGuozhan: true,
	}),
	gz_shamoke: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjili"],
		hasSkinInGuozhan: true,
	}),

	gz_lingcao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdujin"],
	}),
	gz_lifeng: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["tunchu", "shuliang"],
	}),
	gz_beimihu: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzguishu", "gzyuanyu"],
	}),
	gz_jianggan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["weicheng", "daoshu"],
	}),
	gz_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["spwuku", "spmiewu"],
	}),
	gz_huaxin: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wanggui", "fakexibing"],
	}),
	gz_luyusheng: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakezhente", "fakezhiwei"],
	}),
	gz_zongyu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zyqiao", "gzchengshang"],
	}),
	gz_miheng: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakekuangcai", "gzshejian"],
		hasSkinInGuozhan: true,
		dieAudios: ["re_miheng"], 
	}),
	gz_fengxi: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyusui", "gzboyan"],
		hasSkinInGuozhan: true,
	}),
	gz_dengzhi: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzjianliang", "gzweimeng"],
		hasSkinInGuozhan: true,
	}),
	gz_re_nanhualaoxian: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzgongxiu", "gztaidan", "gzjinghe_new"],
	}),
	gz_zhouyi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhukou", "gzduannian", "gzlianyou"],
	}),
	gz_re_xunchen: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzfenglve", "gzanyong"],
	}),
	gz_lvlingqi: new Character({
		sex: "female",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["guowu", "gzshenwei", "gzzhuangrong"],
		hasSkinInGuozhan: true,
	}),
	gz_dc_yanghu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdeshao", "gzmingfa"],
	}),

	///
	gz_cuimao: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhengbi", "gzfengying"],
		hasSkinInGuozhan: true,
	}),
	gz_yujin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjieyue"],
		img: "image/character/yujin.jpg",
		dieAudios: ["yujin"],
	}),
	gz_wangping: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jianglue"],
		hasSkinInGuozhan: true,
	}),
	gz_fazheng: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzxuanhuo", "gzenyuan"],
		hasSkinInGuozhan: true,
		dieAudios: ["xin_fazheng"],
	}),
	gz_wuguotai: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbuyi", "ganlu"],
		img: "image/character/re_wuguotai.jpg",
	}),
	gz_lukang: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakejueyan", "fakekeshou"],
		hasSkinInGuozhan: true,
	}),
	gz_yuanshu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzweidi", "gzyongsi"],
		hasSkinInGuozhan: true,
	}),
	gz_zhangxiu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzfudi", "gzcongjian"],
		hasSkinInGuozhan: true,
	}),
	gz_jun_caocao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jianan", "huibian", "gzzongyu"],
	}),

	gz_jin_zhangchunhua: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuishi", "fakeqingleng"],
	}),
	gz_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakequanbian", "smyyingshi", "fakezhouting"],
	}),
	gz_jin_wangyuanji: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeyanxi", "fakeshiren"],
	}),
	gz_jin_simazhao: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhaoran", "gzchoufa"],
	}),
	gz_jin_xiahouhui: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakebaoqie", "jyishi", "shiduo"],
	}),
	gz_jin_simashi: new Character({
		sex: "male",
		group: "jin",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gzyimie", "gztairan"],
	}),
	gz_duyu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzsanchen", "gzpozhu"],
	}),
	gz_zhanghuyuechen: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakexijue"],
	}),
	gz_jin_yanghuiyu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeciwei", "fakehuirong"],
	}),
	gz_simazhou: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["caiwang", "gznaxiang"],
	}),
	gz_shibao: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhuosheng"],
	}),
	gz_weiguan: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhongyun", "shenpin"],
	}),
	gz_zhongyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbolan", "yifa"],
	}),
	gz_yangyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzxuanbei", "xianwan"],
	}),
	gz_zuofen: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaosong", "gzlisi"],
	}),
	gz_xuangongzhu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeqimei", "ybzhuiji"],
	}),
	gz_xinchang: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakecanmou", "congjian"],
	}),
	gz_yangzhi: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwanyi", "gzmaihuo"],
	}),

	gz_liaohua: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdangxian"],
	}),
	gz_zhugejin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuanshi", "gzhongyuan", "gzmingzhe"],
	}),
	gz_yangxiu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdanlao", "gzjilei"],
	}),
	gz_zumao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["yinbing", "juedi"],
	}),
	gz_fuwan: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzmoukui"],
		img: "image/character/tw_fuwan.jpg",
	}),
	gz_chendao: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["drlt_wanglie"],
	}),
	gz_tw_tianyu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhenxi", "gzjiansu"],
	}),
	gz_tw_liufuren: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhuidu", "gzshigong"],
	}),
	gz_old_huaxiong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzyaowu", "gzshiyong"],
	}),
	gz_tw_xiahoushang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gztanfeng"],
	}),

	gz_xf_huangquan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdianhu", "gzjianji"],
		doubleGroup: ["wei", "shu"],
	}),
	gz_guohuai: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzduanshi", "gzjingce"],
		hasSkinInGuozhan: true,
	}),
	gz_guanqiujian: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhengrong", "gzhongju"],
	}),
	gz_zhujun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzgongjian", "gzkuimang"],
	}),
	gz_chengong: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyinpan", "gzxingmou"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_re_xugong: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiaozhao", "gzyechou"],
		doubleGroup: ["wu", "qun"],
	}),

	gz_yangwan: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyouyan", "gzzhuihuan"],
		hasSkinInGuozhan: true,
	}),

	gz_key_ushio: new Character({
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		hujia: 999,
		skills: ["ushio_huanxin", "ushio_xilv"],
		// 就你势力多
		doubleGroup: ["key", "wei", "shu", "wu", "qun", "jin"],
	}),

	gz_wangling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakemibei"],
	}),
	gz_yanyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakejuzhan"],
	}),
	gz_xin_zhuran: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakedanshou"],
	}),
	gz_gaoshun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakexunxi", "fakehuanjia"],
		hasSkinInGuozhan: true,
	}),
	gz_jin_jiachong: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakexiongshu", "fakejianhui"],
	}),
	gz_jin_yanghu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakechongxin", "fakeweirong"],
	}),
	////////////////////////////////////////////////////////////////////
};

export const intro = {
	gz_caocao: "魏武帝曹操，字孟德，小名阿瞒、吉利，沛国谯人。精兵法，善诗歌，乃治世之能臣，乱世之奸雄也。",
	gz_simayi: "晋宣帝，字仲达，河内温人。曾任职过曹魏的大都督，太尉，太傅。少有奇节，聪明多大略，博学洽闻，伏膺儒教，世之鬼才也。",
	gz_xiahoudun: "字元让，沛国谯人。有拔矢啖睛之勇，性格勇猛刚烈。",
	gz_zhangliao: "字文远，魏雁门马邑人。官至前将军、征东将军、晋阳侯。武功高强，又谋略过人，多次建立奇功，以800人突袭孙权十万大军，皆望风披靡。",
	gz_xuzhu: "字仲康，谯国谯县人。和典韦一同统率着曹操的亲卫队“虎卫军”。因为他十分勇猛，所以有“虎痴”的绰号。曾有裸衣斗马超之举。",
	gz_guojia: "字奉孝，颍川阳翟人，官至军师祭酒。惜天妒英才，英年早逝。有诗云：“良计环环不遗策，每临制变满座惊”。",
	gz_zhenji: "中山无极人，别称甄洛或甄宓，庙号文昭甄皇后。魏文帝曹丕的正室。懂诗文，有倾国倾城之貌，《洛神赋》即是曹植为她所作。",
	gz_xiahouyuan: "字妙才，沛国谯人。东汉末年曹操部下名将，夏侯惇之族弟，八虎骑之一。群雄征讨董卓时随曹操一同起兵，后征战四方，屡立功勋。在平定马超叛乱后负责西北防线的镇守。公元219年刘备攻打汉中，被刘备部将黄忠所杀。",
	gz_zhanghe: "字儁乂，河间鄚人。三国时期魏国名将。官渡之战时，本为袁绍部将的张郃投降了曹操，并在曹操帐下多立功勋，于曹魏建立后加封为征西车骑将军。诸葛亮六出祁山之间，张郃多次抵御蜀军的进攻，于公元231年在木门道被诸葛亮设伏射死。后谥曰壮侯。为曹魏“五子良将”之一。",
	gz_xuhuang: "字公明，河东杨人。三国时期曹魏名将，本为杨奉帐下骑都尉，杨奉被曹操击败后转投曹操，在曹操手下多立功勋，参与官渡、赤壁、关中征伐、汉中征伐等几次重大战役。",
	gz_caoren: "字子孝，沛国谯人，曹操的从弟。三国时期曹魏名将，官至大司马。谥曰忠侯。",
	gz_dianwei: "己吾城村人。东汉末年曹魏猛将。擅使大双戟，为人壮猛任侠，曾为乡人刘氏报仇，杀人出市，人莫敢近。相貌魁梧，膂力过人。建安二年（197），张绣背叛曹操，典韦为保护曹操而独挡叛军，击杀多人，但最终因寡不敌众而战死。",
	gz_xunyu: "荀彧，字文若，颍川颍阴（今河南许昌）人。东汉末年曹操帐下首席谋臣，杰出的战略家。自小被世人称作“王佐之才”。",
	gz_caopi: "字子桓，三国时期著名的政治家、文学家，曹魏的开国皇帝，公元220－226年在位。沛国谯人，魏武帝曹操与武宣卞皇后的长子。去世后庙号高祖，谥为文皇帝，葬于首阳陵。",
	gz_yuejin: "字文谦，魏“五子良将”之一。容貌短小，以胆烈跟从曹操，南征北讨，战功无数。从击袁绍于官渡，奋勇力战，斩袁绍部将淳于琼。又从击袁绍子谭、尚于黎阳，斩其大将严敬。从平荆州，留屯襄阳，进击关羽、苏非等人，击退其众，南郡诸郡的山谷蛮夷都前往乐进处投降。后来从曹操征孙权，假进节。曹操回师后，留乐进与张辽、李典屯于合肥。又以乐进数有军功，迁右将军。建安二十三年逝世，谥曰威侯。",

	gz_liubei: "先主姓刘，讳备，字玄德，涿郡涿县人，汉景帝子中山靖王胜之后也。以仁德治天下。",
	gz_guanyu: "字云长，本字长生，并州河东解州人。五虎上将之首，爵至汉寿亭侯，谥曰“壮缪侯”。被奉为“关圣帝君”，崇为“武圣”。",
	gz_zhangfei: "字翼德，涿郡人，燕颔虎须，豹头环眼。有诗云：“长坂坡头杀气生，横枪立马眼圆睁。一声好似轰雷震，独退曹家百万兵”。",
	gz_zhugeliang: "字孔明，号卧龙，琅琊阳都人，蜀汉丞相。在世时被封为武乡侯，谥曰忠武侯。著有《出师表》、《诫子书》等。怀不世之才，以空城戏司马，能观星象而通鬼神。",
	gz_zhaoyun: "字子龙，常山真定人。身长八尺，姿颜雄伟。长坂坡单骑救阿斗，先主云：“子龙一身都是胆也。”",
	gz_machao: "字孟起，扶风茂陵人。面如冠玉，目如流星，虎体猿臂，彪腹狼腰，声雄力猛。因衣着讲究，举止非凡，故人称“锦马超”。麾铁骑，捻金枪。",
	gz_huangyueying: "荆州沔南白水人，沔阳名士黄承彦之女，诸葛亮之妻，诸葛瞻之母。容貌甚丑，而有奇才：上通天文，下察地理，韬略近于诸书无所不晓，诸葛亮在南阳闻其贤而迎娶。",
	gz_huangzhong: "字汉升，今河南南阳人。汉末三国时期蜀汉名将。本为刘表部下中郎将，后归刘备，并助刘备攻益州刘璋，在定军山一战中阵斩曹操部下名将夏侯渊。备称汉中王后改封后将军，赐关内侯。",
	gz_weiyan: "字文长，义阳人。三国时期蜀汉名将，诸葛亮死后，魏延因被陷害谋反而遭杨仪一党所杀。",
	gz_pangtong: "庞统，字士元，襄阳（治今湖北襄阳）人。三国时刘备帐下谋士，官拜军师中郎将。才智与诸葛亮齐名，人称“凤雏”。在进围雒县时，统率众攻城，不幸被流矢击中去世，时年三十六岁。追赐统为关内侯，谥曰靖侯。庞统死后，葬于落凤庞统墓坡。",
};

export const sort = "guozhan_default";
