import { Character } from "../../../../noname/library/element/index.js";

export default {
	// 分组1：野心家
	gz_zhonghui: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakequanji", "fakepaiyi"],
		hasSkinInGuozhan: true,
	}),
	gz_shimazhao: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaoxin", "gzsuzhi"],
		hasSkinInGuozhan: true,
	}),
	gz_gongsunyuan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzhuaiyi", "gzzisui"],
		hasSkinInGuozhan: true,
	}),
	gz_sunchen: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakeshilu", "fakexiongnve"],
		hasSkinInGuozhan: false,
	}),
	// 分组2：谷爱凌
	gz_tangzi: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxingzhao"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_mengda: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qiuan", "liangfan"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_liuqi: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwenji", "gztunjiang"],
		doubleGroup: ["qun", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_mifangfushiren: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mffengshi"],
		doubleGroup: ["wu", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_shixie: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiluan", "gzrelixia"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhanglu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzrebushi", "gzremidao"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_dongzhao: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["quanjin", "zaoyun"],
		// doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: false,
	}),
	gz_re_xushu: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhuhai", "gzpozhen", "gzjiancai"],
		hasSkinInGuozhan: true,
	}),
	// 那男舅
	gz_wujing: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["donggui", "fengyang"],
		hasSkinInGuozhan: true,
	}),
	// 严虎
	gz_yanbaihu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhidao", "gzyjili"],
		hasSkinInGuozhan: true,
	}),
	gz_xuyou: new Character({
		doubleGroup: ["wei", "qun"],
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenglve", "gzshicai"],
		hasSkinInGuozhan: true,
	}),
	gz_xiahouba: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzbaolie"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_panjun: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzcongcha", "xinfu_gongqing"],
		doubleGroup: ["shu", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_huangzu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxishe"],
		hasSkinInGuozhan: true,
	}),
	gz_zhugeke: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["aocai", "gzduwu"],
		hasSkinInGuozhan: true,
	}),
	gz_wenqin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjinfa"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_xf_sufei: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzlianpian"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_liuba: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongduo", "qingyin"],
		hasSkinInGuozhan: true,
	}),
	gz_pengyang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongling", "gzjinyu"],
		doubleGroup: ["shu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhuling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjuejue", "gzfangyuan"],
		hasSkinInGuozhan: true,
	}),
	gz_wangyi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhenlie", "miji"],
	}),
	gz_wangji: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzqizhi", "gzjinqu"],
	}),
	gz_xurong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxionghuo"],
	}),
	gz_xianglang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzkanji", "dcqianzheng"],
	}),
	gz_tengyin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenjian", "gzxixiu"],
	}),
	gz_re_panshu: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhiren", "gzyaner"],
	}),
	gz_maliang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiemu", "naman"],
		dieAudios: ["old_maliang"],
	}),
	gz_caozhen: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzsidi"],
	}),
	gz_caoang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["kaikang"],
	}),
	gz_bulianshi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["old_anxu", "zhuiyi"],
	}),
	gz_mazhong: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["twfuman"],
	}),
	gz_ol_lisu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiaoyan", "xianzhu"],
	}),
	

	gz_re_xusheng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["repolu"],
	}),
	// 怎么还冒出来一个体力上限不一样的呢？
	gz_ol_sb_sunjian: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		hujia: 0,
		skills: ["olsbhulie", "olsbyipo"],
	}),

	gz_re_lidian: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xunxun", "wangxi"],
	}),
	gz_zangba: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzhengjiang"],
		img: "image/character/tw_zangba.jpg",
	}),
	gz_madai: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mashu", "qianxi"],
		hasSkinInGuozhan: true,
	}),
	gz_mifuren: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzguixiu", "gzcunsi"],
	}),
	gz_sunce: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jiang", "yingyang", "baka_hunshang"],
		hasSkinInGuozhan: true,
	}),
	gz_chendong: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["duanxie", "fakefenming"],
		hasSkinInGuozhan: true,
	}),
	gz_sp_dongzhuo: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["hengzheng", "fakebaoling"],
	}),
	gz_zhangren: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["chuanxin", "fengshi"],
	}),

	gz_jun_liubei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhangwu", "jizhao", "shouyue"],
	}),
	gz_jun_zhangjiao: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["wuxin", "hongfa", "wendao"],
	}),
	gz_jun_sunquan: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jiahe", "lianzi", "jubao"],
	}),

	gz_liqueguosi: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxiongsuan"],
		hasSkinInGuozhan: true,
	}),
	gz_zuoci: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeyigui", "fakejihun"],
		hasSkinInGuozhan: true,
	}),
	gz_bianfuren: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wanwei", "gzyuejian"],
		dieAudios: ["ol_bianfuren"],
	}),
	gz_xunyou: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzqice", "zhiyu"],
		hasSkinInGuozhan: true,
	}),
	gz_lingtong: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xuanlve", "yongjin"],
		hasSkinInGuozhan: true,
	}),
	gz_lvfan: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdiaodu_backports", "gzdiancai"],
		hasSkinInGuozhan: true,
	}),
	gz_masu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzsanyao", "gzzhiman"],
		hasSkinInGuozhan: true,
	}),
	gz_shamoke: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjili"],
		hasSkinInGuozhan: true,
	}),

	gz_lingcao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdujin"],
	}),
	gz_lifeng: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["tunchu", "shuliang"],
	}),
	gz_beimihu: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzguishu", "gzyuanyu"],
	}),
	gz_jianggan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["weicheng", "daoshu"],
	}),
	gz_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["spwuku", "spmiewu"],
	}),
	gz_huaxin: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wanggui", "fakexibing"],
	}),
	gz_luyusheng: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakezhente", "fakezhiwei"],
	}),
	gz_zongyu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zyqiao", "gzchengshang"],
	}),
	gz_miheng: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakekuangcai", "gzshejian"],
		hasSkinInGuozhan: true,
		dieAudios: ["re_miheng"], 
	}),
	gz_fengxi: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyusui", "gzboyan"],
		hasSkinInGuozhan: true,
	}),
	gz_dengzhi: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzjianliang", "gzweimeng"],
		hasSkinInGuozhan: true,
	}),
	gz_re_nanhualaoxian: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzgongxiu", "gztaidan", "gzjinghe_new"],
	}),
	gz_zhouyi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhukou", "gzduannian", "gzlianyou"],
	}),
	gz_re_xunchen: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzfenglve", "gzanyong"],
	}),
	gz_lvlingqi: new Character({
		sex: "female",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["guowu", "gzshenwei", "gzzhuangrong"],
		hasSkinInGuozhan: true,
	}),
	gz_dc_yanghu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdeshao", "gzmingfa"],
	}),
	gz_cuimao: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhengbi", "gzfengying"],
		hasSkinInGuozhan: true,
	}),
	gz_yujin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjieyue"],
		img: "image/character/yujin.jpg",
		dieAudios: ["yujin"],
	}),
	gz_wangping: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jianglue"],
		hasSkinInGuozhan: true,
	}),
	gz_fazheng: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzxuanhuo", "gzenyuan"],
		hasSkinInGuozhan: true,
		dieAudios: ["xin_fazheng"],
	}),
	gz_wuguotai: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbuyi", "ganlu"],
		img: "image/character/re_wuguotai.jpg",
	}),
	gz_lukang: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakejueyan", "fakekeshou"],
		hasSkinInGuozhan: true,
	}),
	gz_yuanshu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzweidi", "gzyongsi"],
		hasSkinInGuozhan: true,
	}),
	gz_zhangxiu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzfudi", "gzcongjian"],
		hasSkinInGuozhan: true,
	}),
	gz_jun_caocao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jianan", "huibian", "gzzongyu"],
	}),
	// 分组3：晋势力
	gz_jin_zhangchunhua: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuishi", "fakeqingleng"],
	}),
	gz_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakequanbian", "smyyingshi", "fakezhouting"],
	}),
	gz_jin_wangyuanji: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeyanxi", "fakeshiren"],
	}),
	gz_jin_simazhao: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhaoran", "gzchoufa"],
	}),
	gz_jin_xiahouhui: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakebaoqie", "jyishi", "shiduo"],
	}),
	gz_jin_simashi: new Character({
		sex: "male",
		group: "jin",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gzyimie", "gztairan"],
	}),
	gz_duyu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzsanchen", "gzpozhu"],
	}),
	gz_zhanghuyuechen: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakexijue"],
	}),
	gz_jin_yanghuiyu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeciwei", "fakehuirong"],
	}),
	gz_simazhou: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["caiwang", "gznaxiang"],
	}),
	gz_shibao: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhuosheng"],
	}),
	gz_weiguan: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhongyun", "shenpin"],
	}),
	gz_zhongyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbolan", "yifa"],
	}),
	gz_yangyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzxuanbei", "xianwan"],
	}),
	gz_zuofen: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaosong", "gzlisi"],
	}),
	gz_xuangongzhu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeqimei", "ybzhuiji"],
	}),
	gz_xinchang: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakecanmou", "congjian"],
	}),
	gz_yangzhi: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwanyi", "gzmaihuo"],
	}),

	gz_liaohua: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdangxian"],
	}),
	gz_zhugejin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuanshi", "gzhongyuan", "gzmingzhe"],
	}),
	gz_yangxiu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdanlao", "gzjilei"],
	}),
	gz_zumao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["yinbing", "juedi"],
	}),
	gz_fuwan: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzmoukui"],
		img: "image/character/tw_fuwan.jpg",
	}),
	gz_chendao: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["drlt_wanglie"],
	}),
	gz_tw_tianyu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhenxi", "gzjiansu"],
	}),
	gz_tw_liufuren: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhuidu", "gzshigong"],
	}),
	gz_old_huaxiong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzyaowu", "gzshiyong"],
	}),
	gz_tw_xiahoushang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gztanfeng"],
	}),

	gz_xf_huangquan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdianhu", "gzjianji"],
		doubleGroup: ["wei", "shu"],
	}),
	gz_guohuai: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzduanshi", "gzjingce"],
		hasSkinInGuozhan: true,
	}),
	gz_guanqiujian: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhengrong", "gzhongju"],
	}),
	gz_zhujun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzgongjian", "gzkuimang"],
	}),
	gz_chengong: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyinpan", "gzxingmou"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_re_xugong: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiaozhao", "gzyechou"],
		doubleGroup: ["wu", "qun"],
	}),

	gz_yangwan: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyouyan", "gzzhuihuan"],
		hasSkinInGuozhan: true,
	}),
	// 神谷爱凌
	gz_key_ushio: new Character({
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		hujia: 999,
		skills: ["ushio_huanxin", "ushio_xilv"],
		// 就你势力多
		doubleGroup: ["key", "wei", "shu", "wu", "qun", "jin"],
	}),

	gz_wangling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakemibei"],
	}),
	gz_yanyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakejuzhan"],
	}),
	gz_xin_zhuran: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakedanshou"],
	}),
	gz_gaoshun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakexunxi", "fakehuanjia"],
		hasSkinInGuozhan: true,
	}),
	gz_jin_jiachong: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakexiongshu", "fakejianhui"],
	}),
	gz_jin_yanghu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakechongxin", "fakeweirong"],
	}),
}

export const sort = "";
