export default {
	gz_caocao: "曹操",
	gz_simayi: "司马懿",
	gz_xiahoudun: "夏侯惇",
	gz_zhangliao: "张辽",
	gz_xuzhu: "许褚",
	gz_guojia: "郭嘉",
	gz_zhenji: "甄宓",
	gz_xiahouyuan: "夏侯渊",
	gz_zhanghe: "张郃",
	gz_xuhuang: "徐晃",
	gz_caoren: "曹仁",
	gz_dianwei: "典韦",
	gz_xunyu: "荀彧",
	gz_caopi: "曹丕",
	gz_yuejin: "乐进",
};
