window.noname_character_perfectPairs = {
	bailingyun: ["jin_simayi"],
	bulianshi: ["sunquan"],
	caifuren: ["liubiao"],
	caoang: ["caocao"],
	caocao: ["xuzhu", "dianwei", "bianfuren"],
	caohong: ["caoren"],
	caopi: ["zhenji", "cuimao"],
	caozhi: ["zhenji"],
	chengong: ["lvbu"],
	chengpu: ["zhouyu"],
	cuiyan: ["caocao"],
	daqiao: ["xiaoqiao"],
	daxiaoqiao: ["zhouyu", "sunce"],
	dingfeng: ["xusheng", "re_xusheng", "zhugeke"],
	dongzhuo: ["liru", "dongbai", "xurong"],
	fuhuanghou: ["liuxie"],
	fuwan: ["fuhuanghou"],
	ganning: ["lingtong", "xf_sufei"],
	guanping: ["guanyu"],
	guanqiujian: ["wenqin"],
	guansuo: ["guanyu"],
	guanyinping: ["guanyu"],
	guanyu: ["zhangfei", "liaohua"],
	hanba: ["swd_muyun"],
	hs_anduin: ["hs_wvelen", "hs_mijiaojisi"],
	hs_jaina: ["hs_antonidas"],
	hs_malfurion: ["hs_malorne"],
	hs_sthrall: ["hs_totemic", "hs_alakir", "hs_neptulon", "hs_yngvar"],
	huangzhong: ["weiyan"],
	jiangqing: ["zhoutai"],
	jiangwei: ["xiahouba"],
	jiaxu: ["liqueguosi"],
	jin_guohuai: ["jin_jiachong"],
	jin_simashi: ["jin_xiahouhui", "jin_yanghuiyu"],
	jin_simayi: ["jin_zhangchunhua", "shibao"],
	jin_simazhao: ["jin_wangyuanji"],
	jin_yanghu: ["duyu"],
	key_ao: ["key_inari"],
	key_chihaya: ["key_sakuya"],
	key_doruji: ["key_rin"],
	key_hinata: ["key_yui"],
	key_iwasawa: ["key_hisako"],
	key_jojiro: ["key_yusa"],
	key_kaori: ["key_shiori"],
	key_komari: ["key_rin", "key_sasami"],
	key_kud: ["key_harukakanata"],
	key_lucia: ["key_shizuru"],
	key_masato: ["key_kengo"],
	key_riki: ["key_rin", "key_saya", "key_kyousuke", "key_kud"],
	key_shiroha: ["key_umi"],
	key_shizuku: ["key_tsumugi"],
	key_tomoya: ["key_nagisa", "key_sunohara", "key_kotomi"],
	key_yuiko: ["key_harukakanata"],
	key_yuri: ["key_kanade", "key_abyusa"],
	key_yuu: ["key_nao"],
	key_yuzuru: ["key_hinata", "key_kanade", "key_ayato"],
	lijue: ["guosi", "jiaxu"],
	lingcao: ["lingtong"],
	lingju: ["diaochan", "lvbu"],
	lingtong: ["ganning"],
	liubei: ["guanyu", "zhangfei", "ganfuren", "fazheng"],
	liuchen: ["liushan"],
	lukang: ["luxun"],
	lvbu: ["diaochan", "lvlingqi"],
	machao: ["madai", "mayunlu", "yangwan"],
	maliang: ["masu"],
	mateng: ["machao", "madai", "mayunlu"],
	menghuo: ["zhurong"],
	nanhualaoxian: ["zuoci", "yuji"],
	pangtong: ["zhugejin"],
	re_guohuai: ["xiahouyuan", "zhanghe"],
	re_nanhualaoxian: ["zuoci", "yuji"],
	re_xushu: ["zhaoyun", "sp_zhugeliang"],
	re_yuanshao: ["yanwen", "tianfeng", "yanliang", "wenchou"],
	simahui: ["pangdegong"],
	simazhao: ["wangyuanji", "simayi"],
	sp_zhugeliang: ["pangtong", "huangyueying"],
	sunben: ["zhouyu", "taishici", "re_taishici", "daqiao"],
	sunce: ["zhouyu", "taishici", "re_taishici", "daqiao"],
	sundeng: ["sunquan", "zhoufei"],
	sunluban: ["quancong"],
	sunquan: ["zhoutai"],
	sunshangxiang: ["liubei"],
	sunxiù: ["simalun"],
	swd_anka: ["swd_kama"],
	swd_chenjingchou: ["swd_yuxiaoxue", "swd_tuobayuer"],
	swd_cheyun: ["swd_huanyuanzhi", "swd_murongshi"],
	swd_duanmeng: ["swd_shangzhang"],
	swd_duguningke: ["swd_yuwentuo", "swd_shanxiaoxiao", "swd_yuchiyanhong"],
	swd_fengtianling: ["swd_huyue", "swd_jiting"],
	swd_fengyu: ["swd_ziqiao"],
	swd_hengai: ["zhugeliang", "sp_zhugeliang"],
	swd_huanyuanzhi: ["swd_jipeng"],
	swd_huzhongxian: ["swd_jiliang", "swd_jipeng", "swd_xiyan"],
	swd_jialanduo: ["swd_zhuoshanzhu"],
	swd_jiangwu: ["swd_zhaoyun"],
	swd_jiliang: ["swd_shuijing", "swd_jipeng"],
	swd_jipeng: ["swd_duopeng"],
	swd_jiuyou: ["swd_zhiyin"],
	swd_lanyin: ["swd_zhiyin"],
	swd_luchengxuan: ["swd_xiarou"],
	swd_murongshi: ["swd_huanyuanzhi", "swd_shuijing"],
	swd_muyun: ["swd_lanyin", "swd_zhiyin", "swd_zhanggao", "xushu"],
	swd_nicole: ["swd_lilian"],
	swd_qi: ["swd_huzhongxian"],
	swd_qiner: ["swd_hengai"],
	swd_rongshuang: ["swd_zhuoshanzhu"],
	swd_septem: ["swd_nicole", "swd_kama", "swd_weida", "swd_wangsiyue", "swd_huiyan"],
	swd_shangzhang: ["swd_situqiang"],
	swd_sikongyu: ["swd_muyue"],
	swd_tuwei: ["swd_hengai"],
	swd_xuanyuanjianxian: ["swd_xuanyuanjiantong"],
	swd_yuli: ["swd_chunyuheng"],
	swd_yuxiaoxue: ["swd_yuwentuo"],
	swd_zhanglie: ["swd_tuobayuer"],
	swd_zhaoyun: ["swd_hengai", "swd_yeyaxi", "zhaoyun"],
	taishici: ["liuyao", "kongrong"],
	tw_liufuren: ["yuanshao"],
	tw_xiahoushang: ["caopi"],
	wangping: ["jiangfei"],
	wuguotai: ["sunjian", "ol_sb_sunjian", "sunshangxiang"],
	wujing: ["sunce", "sunben", "wuguotai"],
	xf_sufei: ["ganning"],
	xiahoudun: ["xiahouyuan", "yujin"],
	xiahoushi: ["zhangfei"],
	xuangongzhu: ["duyu"],
	xugong: ["yanbaihu"],
	xunyou: ["xunyu"],
	//xushu: ["liubei"],
	yuanshu: ["jiling"],
	yuejin: ["re_lidian"],
	yuji: ["zuoci"],
	zhangbao: ["zhangliang", "zhangjiao"],
	zhangchunhua: ["simayi"],
	zhangji: ["zhangxiu", "zoushi"],
	zhangliang: ["zhangjiao"],
	zhangliao: ["zangba"],
	zhangqiying: ["zhanglu"],
	zhangxingcai: ["liushan"],
	zhangxiu: ["jiaxu"],
	zhaoyun: ["liushan"],
	zhonghui: ["jiangwei"],
	zhoucang: ["guanyu"],
	zhouyu: ["huanggai", "xiaoqiao", "zhouyi"],
	zhugejin: ["zhugeke", "sunquan"],
	zhugeliang: ["jiangwei", "jiangfei", "huangyueying"],
	zuoci: ["yuji"],
};
